### PR TITLE
Task 4

### PR DESCRIPTION
**Pull request by bdvx**
[Task 4](https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/4f716e89de0ed3896f0f758db62fff8132e2c868/task4-rds/task.md)

* [ ] Task 4.1 is implemented
* [ ] Task 4.2 is implemented lambda links are provided and returns data
* [ ] Task 4.3 is implemented lambda links are provided and products is stored in DB (call TASK 4.2 to see the product)
* [ ] Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend. Link to a working Front-End application is provided for cross-check reviewer.

**Additional (optional) tasks:**

* [ ]  POST/products lambda functions returns error 400 status code if product data is invalid
* [ ]  All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
* [ ]  All lambdas do console.log for each incoming requests and their arguments
* [ ]  Transaction based creation of product (in case stock creation is failed then related to this stock product is not created and not ready to be used by the end user and vice versa) (https://devcenter.kinvey.com/nodejs/tutorials/bl-transactional-support)

Endpoints:
[getProductsList](https://755vvfmegj.execute-api.eu-west-1.amazonaws.com/dev/products) (GET)
[getProductById](https://755vvfmegj.execute-api.eu-west-1.amazonaws.com/dev/products/2899eeff-9710-40d7-83b3-25385b16582a) (GET)
[createProduct](https://755vvfmegj.execute-api.eu-west-1.amazonaws.com/dev/products) (POST)

Swagger API link - https://app.swaggerhub.com/apis/bdvx/rs-app-aws-product-api/1.0.0 (or you can access swagger.json in repo)

FE repo - https://github.com/bdvx/nodejs-aws-fe

FE link - http://rs-app-aws-fe.s3-website-eu-west-1.amazonaws.com/

### CODE REVIEW

**Comment by maximsan** [comment]
Hello!
Could you check your backend?
I've got 500 from server
image
Please, attach you lambda in pr too. Thanks!

**Comment by balabukha** [comment]
endpoints doesn't work

**Comment by bdvx** [comment]
@maximsan @balabukha thanks for comments, now all should be up and running!

**Comment by maximsan** [comment]
Hello, @bdvx. I rechecked and it looks like everything works except front-end integration.

**Review by balabukha — APPROVED** [review]

**Review by maximsan — APPROVED** [review]

**Pull request merged**
