### PR TITLE
Task 7

### PR DESCRIPTION
**Pull request by bdvx**
[Task 7](https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task7-lambda%2Bcognito-authorization/task.md)

[URL to execute the /import path of the import-service](https://77upjvo4f6.execute-api.eu-west-1.amazonaws.com/dev/import) (GET)
Header: Authorization Basic YmR2eD1URVNUX1BBU1NXT1JE

[link to check FE](http://rs-app-aws-fe.s3-website-eu-west-1.amazonaws.com/admin/products)
to test - localStorage.setItem('authorization_token', 'YmR2eD1URVNUX1BBU1NXT1JE');

1 - authorization-service is added to the repo, has correct basicAuthorizer lambda and correct serverless.yaml file
3 - import-service serverless.yaml file has authorizer configuration for the importProductsFile lambda. Request to the importProductsFile lambda should work only with correct authorization_token being decoded and checked by basicAuthorizer lambda. Response should be in 403 HTTP status if access is denied for this user (invalid authorization_token) and in 401 HTTP status if Authorization header is not provided.
5 - update client application to send Authorization: Basic authorization_token header on import. Client should get authorization_token value from browser localStorage https://developer.mozilla.org/ru/docs/Web/API/Window/localStorage authorization_token = localStorage.getItem('authorization_token')
Additional (optional) tasks
+1 - Client application should display alerts for the responses in 401 and 403 HTTP statuses. This behavior should be added to the nodejs-aws-fe-main/src/index.tsx file

### CODE REVIEW

**Comment by maksumov** [comment]
Hi. Ping me back if you'll do any tasks. If I can, I'll correct the score

**Comment by bdvx** [comment]
@maksumov can you please check again?

**Comment by maksumov** [comment]
image

I receive HTTP 401 trying to upload CSV file with header `Authorization: Basic YmR2eDpURVNUX1BBU1NXUkQ=`.
That's not correct. It should be 200 (Ok) or 403 (Wrong credentials). Also 401 error not handled.

image

**Comment by bdvx** [comment]
@maksumov redone FE error handling, and added explicit error status in alert, now should be working as intended

**Comment by maksumov** [comment]
@bdvx I saw 401 errors being handled, but I can't test any other functionality. How do I get something other than a 401 error? Requests were made with `localStorage.setItem ('authorization_token', btoa('bdvx:TEST_PASSWORD'))`

**Pull request merged**
